INSERT INTO MOB_ERROR_CODES (ID_ERROR_CODE, ID_ERROR_LEVEL, STR_INFORMATION) VALUES (10101, 'INFO', 'NAME ON BLACKLIST:Name has been on blacklist');
INSERT INTO MOB_ERROR_CODES (ID_ERROR_CODE, ID_ERROR_LEVEL, STR_INFORMATION) VALUES (10102, 'INFO', 'NAME PROBABLE ON BLACKLIST: Name has a likely match on blacklist');

INSERT INTO CUS_BLACKLIST_TYPES (ID_BLACKLIST_TYPE, STR_BLACKLIST_TYPE) VALUES (0, 'OFAC');
