INSERT INTO MOB_UMGR_PRIVILEGES (ID_PRIVILEGE,STR_PRIVILEGE,DAT_CREATION,ID_CUSTOMER_CREATION) values ('WS_SPECIAL_AUTHORISATION','Allows to create a new attribute for a customer',null,0);
INSERT INTO MOB_UMGR_ROLE_PRIVILEGES (ID_ROLE, ID_PRIVILEGE, ID_CUSTOMER_CREATION) VALUES ('SYSTEM','WS_SPECIAL_AUTHORISATION', 0);

