-- root nodes
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer','node',null,'java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer','read_privilege','PREFS_READ_PRESLAYER','java.lang.String','required privilege for reading from this tree',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer','write_privilege','PREFS_WRITE_PRESLAYER','java.lang.String','required privilege for writing to this tree',#CURRENT_TIMESTAMP#,0);

-- insert web application preferences
insert into MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/util/tools/wicketutils/services/Configuration/','mobiliser.password','{AES-128-PBKDF2}5iO6buFt6t+nuo6AvD3bLhnjhf7rmDC5AkhXIDkywwQ=','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
insert into MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/util/tools/wicketutils/services/Configuration/','mobiliser.url','${MOBILISER_HOST}/mobiliser','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
insert into MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/util/tools/wicketutils/services/Configuration/','mobiliser.user','mobiliser','java.lang.String',null,#CURRENT_TIMESTAMP#,0);

INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','assignCpnSupportedIdent','0,1,5','java.lang.String','Supported Identification types for assign coupon',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','merchantAgentTypeIds','8','java.lang.String','comma separated customer type id of agents acting on behalf of merchants',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','airTimeTopupPiClass','0','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','balanceAlertTemplate','consumer.balance.alert','java.lang.String','Default Template for Balance Alert for Consumers',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','bankAccKeyAlias','mobiliser_bank','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','changeMsisdnTemplate','CUSTOMER_MSISDN_OTP','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','changeMsisdnTemplateType','sms','java.lang.String','Specifies the type of template used to send OTP while changing MSISDN',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','channelForTestMessage','defaultQ','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','collatorDecompositionMode','0','java.lang.String','Collator decomposition mode used for sorting dropdown entries',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','collatorStrength','0','java.lang.String','Collator strength used for sorting dropdown entries',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','creditCardKeyAlias','mobiliser_card','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','creditDebitCustomerId','201','java.lang.Long',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','creditDebitPiId','20001','java.lang.Long',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','cstAuditCategories','SYSTEM,READ,CONFIG,SEC','java.lang.String','available audit categories',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','cstRegisterCustomerTypes','2,3,8,9,10,11,101,102','java.lang.String','Customer types which can be created in CST customer registration',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','cstUploadBulkFileTypes','1,2,15,16','java.lang.String','Bulk files of only these types are allowed to be uploaded from CST',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','currency','EUR','java.lang.String','Default currency',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','dashboardServerList','','java.lang.String','Comma separated list of mobiliser server URLs accessible through dashboard',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','defaultCountryCode','49','java.lang.String','Default Country Code',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','defaultCountryId','DE','java.lang.String','Default Country Id',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','defaultLanguage','en','java.lang.String','Default Language',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','defaultSVAAlias','SVA','java.lang.String','Default alias for SVA',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','defaultTypeIdForInternalCustomer','0','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','defaultTypeIdForNewCustomer','2','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','defaultTypeIdForNewCustomerDpp','2','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','dppUploadBulkFileTypes','11,12','java.lang.String','Bulk files of only these types are allowed to be uploaded from DPP',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','isKeyStoreLocal','false','java.lang.Boolean','Specifies whether the installation uses local keystore file for encryption',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','isTestConsumer','false','java.lang.Boolean',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','keyStorePw','{AES-128-PBKDF2}po/pv8BAfbp46awKFo3C+l6AKt3sDgMeDPQAusasFBw=','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','keyStoreType','JCEKS','java.lang.String','The type of keystore which is used',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','maxRecordsForReport','500','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','msisdnOtpConfirmed','false','java.lang.Boolean',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','otpTemplateType','sms','java.lang.String','Specifies the type of template used to send OTP during customer registration',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','publicKeyStore','mobiliser_pub.jks','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','reportPassword','{AES-128-PBKDF2}S20UL/hRA4Q1y6c9QLCscTLTYORIrm+NdvkMnUZVY2A=','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','reportProxyServerPath','/ReportViewer','java.lang.String','Default Crystal Reports viewer path',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','reportProxyServerUrl','${MOBILISER_HOST}/crystalrpt','java.lang.String','URL for the real server url behind the Crystal Reports Proxy',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','reportServerUrl','ReportViewer','java.lang.String','URL for the Crystal Reports Viewer',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','reportUserName','reportsread','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','resetPasswordTemplateType','email','java.lang.String','Specifies the type of template used to send OTP while resetting the password',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','resetPinTemplateType','sms','java.lang.String','Specifies the type of template used to send OTP while resetting the pin',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','riskcategories','0,1,2,3,4,5,6,7','java.lang.String','risk category id''s to be shown in KYC upgrade page',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','smsOtpTemplate','otpsignup','java.lang.String', null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','svaCurrency','EUR','java.lang.String',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','txnCancelTimeBufferInSec','600','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','txnMaxNumberToFetch','1000','java.lang.Integer','Max Txn number',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','useCaseAirtimeTopup','173','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','useCaseCashIn','171','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','useCaseCashOut','172','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','useCaseCreditSva','180','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','useCaseDebitSva','181','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','useCasePickup','175','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','useCaseSendMoneyToBank','161','java.lang.Integer','use Case Id for Send Money To Bank',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/Configuration/','useCaseTransfer','179','java.lang.Integer',null,#CURRENT_TIMESTAMP#,0);

INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/DynamicServiceConfiguration/','mobiliser.password','{AES-128-PBKDF2}2paqrFkmErN0+k7fxg+JX/c5psPmYJK1RODVQGlBf8U=','java.lang.String','Password used to access remote management services',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/DynamicServiceConfiguration/','mobiliser.protocol','${MOBILISER_PROTOCOL}','java.lang.String','Protocol used to access remote management services',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE,STR_PATH,STR_NAME,STR_VALUE,STR_TYPE,STR_DESCRIPTION,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'/presentationlayer/system/com/sybase365/mobiliser/web/util/DynamicServiceConfiguration/','mobiliser.user','mobiliser','java.lang.String','Username used to access remote management services',#CURRENT_TIMESTAMP#,0);

