INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', '_channelType', 'email', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', '_active', 'false', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'channelId', 'defaultQ', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'mail.host', 'localhost', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'mail.port', '25', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'mail.username', '', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'mail.password', '', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'mail.protocol', 'smtp', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'mail.sign', 'false', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'sign.hashAlgorithm', '-1', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'sign.keyId', '-1', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'sign.passphrase', '', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/emailchannel1/', 'sign.secretRingResource', '', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);

INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/gcmchannel1/', '_channelType', 'gcm', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/gcmchannel1/', '_active', 'false', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/gcmchannel1/', 'channelId', 'defaultQ', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);

INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/htmlchannel1/', '_channelType', 'html', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/htmlchannel1/', '_active', 'true', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/htmlchannel1/', 'urlSupplement', 'html', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/htmlchannel1/', 'channelId', 'defaultQ', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);

INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/httpchannel1/', '_channelType', 'http', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/httpchannel1/', '_active', 'true', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/httpchannel1/', 'urlSupplement', 'http', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/httpchannel1/', 'channelId', 'defaultQ', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/httpchannel1/', 'incomingChannelId', 'brandInQueue', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);

INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/jabberchannel1/', '_channelType', 'jabber', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/jabberchannel1/', '_active', 'false', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/jabberchannel1/', 'channelId', 'defaultQ', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/jabberchannel1/', 'incomingChannelId', 'brandInQueue', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/jabberchannel1/', 'xmppHost', 'jabber.org', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/jabberchannel1/', 'xmppPassword', '', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/jabberchannel1/', 'xmppPort', '5222', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/jabberchannel1/', 'xmppServiceName', 'jabber.org', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/jabberchannel1/', 'xmppUsername', '', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);

INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppchannel1/', '_channelType', 'smpp', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppchannel1/', '_active', 'false', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppchannel1/', 'channelId', 'defaultQ', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppchannel1/', 'incomingChannelId', 'brandInQueue', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppchannel1/', 'bindType', 'transceiver', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppchannel1/', 'sendAsDataSm', 'false', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppchannel1/', 'registeredDelivery', '0', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppchannel1/', 'smscTimeZone', '', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);

INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppushchannel1/', '_channelType', 'smpPush', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppushchannel1/', '_active', 'false', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppushchannel1/', 'channelId', 'defaultQ', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppushchannel1/', 'smpBaseUrl', 'http://localhost:8080/', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppushchannel1/', 'appId', 'com.sap.MyApp', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppushchannel1/', 'senderUsername', 'push', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
INSERT INTO MOB_PREFERENCES (ID_PREFERENCE, STR_PATH, STR_NAME, STR_VALUE, STR_TYPE, STR_DESCRIPTION, DAT_CREATION, ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50, '/businesslayer/system/com/sybase365/mobiliser/util/messaging/channelmanager/engine/impl/ChannelInstantiator/smppushchannel1/', 'senderPassword', 'secret', 'java.lang.String', null, #CURRENT_TIMESTAMP#, 0);
