-- Location based Alert example
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.location.coupon',null,'625477','sms','Don not miss it! there is a new coupon for ${get.couponHeader} available that can be redeemed next to you.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.location.coupon','New Coupon Available near to you','mobiliser@sybase.com','email','Don not miss it! there is a new coupon for ${get.couponHeader} available that can be redeemed next to you.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);

Insert into ALR_TYPE (ID_ALERT_TYPE,STR_NAME,STR_DESCRIPTION,BOL_IS_ACTIVE,DAT_CREATION,ID_CUSTOMER_CREATION) values (20,'LocationAlert','Notifies user of new coupon in its alert area.','Y',#CURRENT_TIMESTAMP#,0);

Insert into ALR_TYPE (ID_ALERT_TYPE,STR_NAME,STR_DESCRIPTION,BOL_IS_ACTIVE,DAT_CREATION,ID_CUSTOMER_CREATION) values (40,'NewsLetterAlert','Sends a personalised newletter','Y',#CURRENT_TIMESTAMP#,0);


Insert into ALR_METADATA (ID_ALERT_METADATA,ID_ALERT_TYPE,STR_KEY,STR_TYPE,DAT_CREATION,ID_CUSTOMER_CREATION) values(#SEQ_VAL# * 50,20,'alertLatitude','Double',#CURRENT_TIMESTAMP#,0);
Insert into ALR_METADATA (ID_ALERT_METADATA,ID_ALERT_TYPE,STR_KEY,STR_TYPE,DAT_CREATION,ID_CUSTOMER_CREATION) values(#SEQ_VAL# * 50,20,'alertLongitude','Double',#CURRENT_TIMESTAMP#,0);
Insert into ALR_METADATA (ID_ALERT_METADATA,ID_ALERT_TYPE,STR_KEY,STR_TYPE,DAT_CREATION,ID_CUSTOMER_CREATION) values(#SEQ_VAL# * 50,20,'alertRadius','Long',#CURRENT_TIMESTAMP#,0);
Insert into ALR_METADATA (ID_ALERT_METADATA,ID_ALERT_TYPE,STR_KEY,STR_TYPE,DAT_CREATION,ID_CUSTOMER_CREATION) values(#SEQ_VAL# * 50,20,'customerLatitude','Double',#CURRENT_TIMESTAMP#,0);
Insert into ALR_METADATA (ID_ALERT_METADATA,ID_ALERT_TYPE,STR_KEY,STR_TYPE,DAT_CREATION,ID_CUSTOMER_CREATION) values(#SEQ_VAL# * 50,20,'customerLongitude','Double',#CURRENT_TIMESTAMP#,0);
Insert into ALR_METADATA (ID_ALERT_METADATA,ID_ALERT_TYPE,STR_KEY,STR_TYPE,DAT_CREATION,ID_CUSTOMER_CREATION) values(#SEQ_VAL# * 50,20,'messageParams','String',#CURRENT_TIMESTAMP#,0);

Insert into ALR_NOTIF_MSG (ID_ALERT_NOTIF_MSG,ID_ALERT_TYPE,ID_ALERT_NOTIF_MSG_TYPE,STR_NAME,BOL_IS_ACTIVE,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,20,1,'alert.location.coupon','Y',#CURRENT_TIMESTAMP#,0);
insert into ALR_NOTIF_MSG (ID_ALERT_NOTIF_MSG,ID_ALERT_TYPE,ID_ALERT_NOTIF_MSG_TYPE,STR_NAME,BOL_IS_ACTIVE,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,40,1,'alert.newsletter','Y',#CURRENT_TIMESTAMP#,0);

-- MSG TEMPLATES FOR ALERTS
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.account.balance.summary',null,'625477','sms','Your closing balance for account ${get.accountPiAlias} is ${get.accountPiCurrency} ${get.accountPiBalanceDisplay}','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.account.balance.summary','Account Closing Balance','mobiliser@sybase.com','email','Your closing balance for account ${get.accountPiAlias} is ${get.accountPiCurrency} ${get.accountPiBalanceDisplay}','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.account.balance.threshold',null,'625477','sms','Your closing balance for account ${get.accountPiAlias} is ${get.accountPiCurrency} ${get.accountPiBalanceDisplay}. You get this alert if your balance is under ${get.accountPiCurrency} ${get.customerMinAmountDisplay} or exceeds ${get.accountPiCurrency} ${get.customerMaxAmountDisplay}.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.account.balance.threshold','Account Balance Threshold','mobiliser@sybase.com','email','Your closing balance for account ${get.accountPiAlias} is ${get.accountPiCurrency} ${get.accountPiBalanceDisplay}. You get this alert if your balance is under ${get.accountPiCurrency} ${get.customerMinAmountDisplay} or exceeds ${get.accountPiCurrency} ${get.customerMaxAmountDisplay}.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.failed.attempt.lockout',null,'625477','sms','Your account is locked out due to invalid credentials.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.failed.attempt.lockout','Access Lockout','mobiliser@sybase.com','email','Your account is locked out due to invalid credentials.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.invalid.account.access.text',null,'625477','sms','Invalid access attempted on your account.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.invalid.account.access.conv',null,'625477','sms','Invalid access attempted on your account. Do you want to login again?','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.invalid.account.access.text','Invalid Account Access','mobiliser@sybase.com','email','Invalid access attempted on your account.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.invalid.account.access.conv','Invalid Account Access','mobiliser@sybase.com','email','Invalid access attempted on your account. Do you want to login again?','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.password.changed',null,'625477','sms','Your password has been changed.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.password.changed','Password Changed','mobiliser@sybase.com','email','Your password has been changed.','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.txn.summary.notification',null,'625477','sms','Matching transactions: ${get.transactions}','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.txn.summary.notification','Transaction Summary Notification','mobiliser@sybase.com','email','Matching transactions: ${get.transactions}','text/plain','us-ascii',null,null,'N',#CURRENT_TIMESTAMP#,0);

insert into MSG_TEMPLATES(ID_TEMPLATE,STR_NAME,STR_LANGUAGE,STR_COUNTRY,STR_VARIANT,STR_SUBJECT,STR_SENDER,STR_TEMPLATE_TYPE,STR_CONTENT,STR_CONTENT_TYPE,STR_CHARSET,STR_ALT_CONTENT,STR_ALT_CONTENT_TYPE,STR_ALT_CHARSET,BOL_IS_CONFIDENTIAL,STR_PRINCIPAL_MSG,DAT_CREATION,ID_CUSTOMER_CREATION) values (#SEQ_VAL# * 50,'alert.newsletter',null,null,null,'New Newsletter','mobiliser@sybase.com','email','Hello ${get.firstName} ${get.lastName},some newsletterish stuff...','text/plain','us-ascii',null,null,null,'N',null,#CURRENT_TIMESTAMP#,0);
