INSERT INTO MOB_TNCS (ID_TNC, BOL_ACTIVE, STR_DESCRIPTION, ID_CUSTOMER_CREATION, DAT_CREATION) VALUES (1, 'Y', 'Standard Money Terms and Conditions', 0, #CURRENT_TIMESTAMP#);
INSERT INTO MOB_TNC_VERSIONS (ID_TNC_VERSION, ID_TNC, INT_VERSION, STR_CAPTION, STR_TEXT, STR_URL, ID_CUSTOMER_CREATION, DAT_CREATION) VALUES (#SEQ_VAL# * 50, 1, 1, 'Money Mobiliser Terms and Conditions', 'ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.

Sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat, duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.', 'https://www.google.de/search?q=terms+and+conditions', 0, #CURRENT_TIMESTAMP#);
INSERT INTO MOB_TNCS (ID_TNC, BOL_ACTIVE, STR_DESCRIPTION, ID_CUSTOMER_CREATION, DAT_CREATION) VALUES (2, 'Y', 'Optional Money Terms and Conditions', 0, #CURRENT_TIMESTAMP#);
INSERT INTO MOB_TNC_VERSIONS (ID_TNC_VERSION, ID_TNC, INT_VERSION, STR_CAPTION, STR_TEXT, STR_URL, ID_CUSTOMER_CREATION, DAT_CREATION) VALUES (#SEQ_VAL# * 50, 2, 2, 'Money Mobiliser Newsletter', 'When you join any of our mailing lists your contact details become part of mailing list database. That database enables us to send you information about events, special offerings and promotions in Money Mobiliser.', 'https://www.google.de/search?q=terms+and+conditions', 0, #CURRENT_TIMESTAMP#);

INSERT INTO MOB_SVC_PKGS (ID_SVC_PKG, STR_SVC_PKG, ID_CUSTOMER, ID_ORGUNIT, ID_CUSTOMER_TYPE, BOL_ACTIVE, BOL_SELF_REGISTRATION, BOL_AUTO_ASSIGN, INT_MAX_ASSIGN_PER_CUST, ID_CUSTOMER_CREATION, DAT_CREATION) VALUES (1, 'Money Mobiliser Consumer', 100, '0000', 2, 'Y', 'N', 'Y', 1, 0, #CURRENT_TIMESTAMP#);

INSERT INTO MOB_SVC_PKG_TNCS (ID_ENTITY, ID_SVC_PKG, ID_TNC, BOL_MANDATORY, ID_CUSTOMER_CREATION, DAT_CREATION) VALUES (#SEQ_VAL# * 50, 1, 1, 'Y', 0, #CURRENT_TIMESTAMP#);
INSERT INTO MOB_SVC_PKG_TNCS (ID_ENTITY, ID_SVC_PKG, ID_TNC, BOL_MANDATORY, ID_CUSTOMER_CREATION, DAT_CREATION) VALUES (#SEQ_VAL# * 50, 1, 2, 'N', 0, #CURRENT_TIMESTAMP#);

