INSERT into MOB_AUTH_METHOD_RULE_STEPS (ID_AUTHENTICATION_METHOD_RULE,INT_ORDER,ID_CURRENCY,AMNT_MAX_AMOUNT_ALLOWED,ID_AUTHENTICATION_METHOD,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (9,1,'USD',null,9,#CURRENT_TIMESTAMP#,0);

INSERT INTO MOB_RESTRICTIONS_GROUPS (ID_RESTRICTIONS_GROUP,STR_RESTRICTIONS_GROUP,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (0, 'Default',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_RESTRICTIONS_GROUPS (ID_RESTRICTIONS_GROUP,STR_RESTRICTIONS_GROUP,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (1, 'Risk Group',#CURRENT_TIMESTAMP#,0);

INSERT INTO MOB_ORGUNITS (ID_ORGUNIT,STR_ORGUNIT,ID_CURRENCY,PRC_VAT,ID_TIME_ZONE,ID_COUNTRY,ID_LANGUAGE,ID_LEGAL_ADDRESS,ID_FEE_SET,ID_LIMIT_SET,INT_AUTO_CANCEL_AFTER_MINUTES,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES ('1111','SoapUI','USD',0,'America/New_York',null,'en',null,null,null,null,#CURRENT_TIMESTAMP#,0);

INSERT INTO MOB_USE_CASES (ID_USE_CASE,STR_USE_CASE,BOL_IS_ACTOR_PAYEE,BOL_DISABLE_LIMITS,BOL_IS_PUBLIC,BOL_ALLOW_DIFFERING_AMOUNT,BOL_ALLOW_IDENTCL_PAYER_PAYEE,BOL_ALLOW_ANON_PARTICIPANT,BOL_COPY_EX_RATE_FROM_AUTH,INT_AUTO_CANCEL_AFTER_MINUTES,BOL_AUTO_CAPTURE_REQUIRED,BOL_AUTO_CAPTURE_FORBIDDEN,DAT_CREATION,ID_CUSTOMER_CREATION)VALUES (600,'TEST USE CASE','N','N','N','N','N','N','N',NULL,'N','N',#CURRENT_TIMESTAMP#,0);

INSERT INTO MOB_CUSTOMER_ATTRIBUTE_TYPES(ID_CUSTOMER_ATTRIBUTE_TYPE,STR_CUSTOMER_ATTRIBUTE_TYPE,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (111,'ATTRTYPE',#CURRENT_TIMESTAMP#,0);

INSERT INTO MOB_CUSTOMER_TYPES (ID_CUSTOMER_TYPE,STR_CUSTOMER_TYPE,ID_RISK_CATEGORY,BOL_IS_INTERNAL,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (4,'TEST',0,'N',#CURRENT_TIMESTAMP#,0);

-- adding the test data for otp (adding an OTP_TYPE)
INSERT INTO MOB_OTP_TYPES (ID_OTP_TYPE,STR_OTP_TYPE,BOL_IS_NUMERIC,INT_LENGTH,INT_MAX_WRONG_ENTRIES,ID_MSG_TEMPLATE,STR_MSG_TEMPLATE_TYPE,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (40,'CUSTOMER REGISTRATION OTP','N',6,10,'OTPSIGNUP','sms',#CURRENT_TIMESTAMP#,0);

