INSERT INTO MOB_AUTH_METHODS (ID_AUTHENTICATION_METHOD, STR_AUTHENTICATION_METHOD, DAT_CREATION, ID_CUSTOMER_CREATION) values (500,'Paypal Auth Token',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_AUTH_METHOD_RULES (ID_AUTHENTICATION_METHOD_RULE, STR_AUTHENTICATION_METHOD_RULE, DAT_CREATION, ID_CUSTOMER_CREATION) values (500,'Paypal Auth Token',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_AUTH_METHOD_RULE_STEPS (ID_AUTHENTICATION_METHOD_RULE, INT_ORDER, ID_CURRENCY, ID_AUTHENTICATION_METHOD, DAT_CREATION, ID_CUSTOMER_CREATION) values (500, 1, 'EUR', 500,#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_AUTH_METHOD_RULE_STEPS (ID_AUTHENTICATION_METHOD_RULE, INT_ORDER, ID_CURRENCY, ID_AUTHENTICATION_METHOD, DAT_CREATION, ID_CUSTOMER_CREATION) values (500, 1, 'USD', 500,#CURRENT_TIMESTAMP#,0);

-- INSERTING into MOB_PI_TYPES
INSERT INTO MOB_PI_TYPES (ID_PI_TYPE,STR_PI_TYPE,ID_ISSUER,ID_PI_CLASS,BOL_CREDIT_ALLOWED,BOL_DEBIT_ALLOWED,ID_SETTLEMENT_INSTRUMENT,ID_SETTLEMENT_MODE,ID_FEE_SETTLEMENT_MODE,ID_BOOKING_MODE,ID_DEFAULT_CLEARING_MODE,ID_DEFAULT_FEE_CLEARING_MODE,BOL_EXTERNAL_CLEARING_CONTROL,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (75,'Paypal External Account',null,7,'Y','Y',null,'none',null,0,null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PI_TYPES (ID_PI_TYPE,STR_PI_TYPE,ID_ISSUER,ID_PI_CLASS,BOL_CREDIT_ALLOWED,BOL_DEBIT_ALLOWED,ID_SETTLEMENT_INSTRUMENT,ID_SETTLEMENT_MODE,ID_FEE_SETTLEMENT_MODE,ID_BOOKING_MODE,ID_DEFAULT_CLEARING_MODE,ID_DEFAULT_FEE_CLEARING_MODE,BOL_EXTERNAL_CLEARING_CONTROL,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (76,'Paypal Merchant Account',null,7,'Y','Y',null,'none',null,0,null,null,'N',#CURRENT_TIMESTAMP#,0);
INSERT INTO MOB_PI_TYPES (ID_PI_TYPE,STR_PI_TYPE,ID_ISSUER,ID_PI_CLASS,BOL_CREDIT_ALLOWED,BOL_DEBIT_ALLOWED,ID_SETTLEMENT_INSTRUMENT,ID_SETTLEMENT_MODE,ID_FEE_SETTLEMENT_MODE,ID_BOOKING_MODE,ID_DEFAULT_CLEARING_MODE,ID_DEFAULT_FEE_CLEARING_MODE,BOL_EXTERNAL_CLEARING_CONTROL,DAT_CREATION,ID_CUSTOMER_CREATION) VALUES (77,'Paypal Consumer Account',null,7,'Y','Y',null,'none',null,0,null,null,'N',#CURRENT_TIMESTAMP#,0);

-- INSERTING into MOB_AUTH_MATRIX
INSERT INTO MOB_AUTH_MATRIX (ID_ENTITY,ID_AUTHENTICATION_METHOD_RULE,DAT_CREATION,ID_CUSTOMER_CREATION,ID_USE_CASE,ID_PI_TYPE,BOL_IS_PAYER) VALUES (#SEQ_VAL# * 50,500,#CURRENT_TIMESTAMP#,0,191,77,'Y');
INSERT INTO MOB_AUTH_MATRIX (ID_ENTITY,ID_AUTHENTICATION_METHOD_RULE,DAT_CREATION,ID_CUSTOMER_CREATION,ID_USE_CASE,ID_PI_TYPE,BOL_IS_PAYER) VALUES (#SEQ_VAL# * 50,500,#CURRENT_TIMESTAMP#,0,701,77,'Y');

